name: Build, Test, and Export Web

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build-and-test:
    name: Build, Test & Export Web
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          # 暂时保留缓存，看看是否有影响
          cache: 'yarn'

      # --- 诊断步骤 1 ---
      - name: Check Yarn version (Before Corepack Enable)
        run: |
          echo "Node version: $(node --version)"
          echo "NPM version: $(npm --version)"
          echo "Yarn path: $(which yarn || echo 'yarn not found')"
          echo "Yarn version: $(yarn --version || echo 'yarn not found')"
          echo "Corepack version: $(corepack --version || echo 'corepack not found')"

      # --- 明确启用 Corepack ---
      - name: Enable Corepack
        run: corepack enable

      # --- 诊断步骤 2 ---
      - name: Check Yarn version (After Corepack Enable)
        run: |
          echo "Yarn path: $(which yarn || echo 'yarn not found')"
          echo "Yarn version: $(yarn --version || echo 'yarn not found')"

      - name: Install dependencies
        run: |
          echo "Attempting yarn install..."
          # 再检查一次版本，确保没变回去
          yarn --version
          yarn install --immutable

      # --- 后续步骤保持不变 ---
      - name: Run Lint
        run: yarn lint

      - name: Run Tests
        run: yarn test --ci --watchAll=false

      - name: Type Check
        run: yarn tsc --noEmit

      - name: Build Web App (Expo Export)
        run: npx expo export

      - name: Upload Web Build Artifact
        uses: actions/upload-artifact@v4
        with:
          name: web-build-output
          path: ./dist
          if-no-files-found: error
