name: Build, Test, and Export Web # Workflow name

on: # Define triggers
  push:
    branches: [ main ] # On push to main branch
  pull_request:
    branches: [ main ] # On Pull Request targeting main branch
  workflow_dispatch: # Allow manual trigger

jobs:
  build-and-test: # Job ID
    name: Build, Test & Export Web # Job name shown on GitHub
    runs-on: ubuntu-latest # Runner environment
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'yarn'

      # --- Add this step ---
      - name: Enable Corepack
        run: corepack enable
      # --- End of added step ---

      - name: Install dependencies
        run: yarn install --immutable # Now this will use Yarn 4.9.1 managed by Corepack

      - name: Run Lint
        run: yarn lint

      - name: Run Tests
        run: yarn test --ci --watchAll=false

      - name: Type Check
        run: yarn tsc --noEmit

      - name: Build Web App (Expo Export)
        run: npx expo export

      - name: Upload Web Build Artifact
        uses: actions/upload-artifact@v4
        with:
          name: web-build-output
          path: ./dist
          if-no-files-found: error
          
